# fly.toml app configuration file generated for itsyourturn on 2026-03-24T22:27:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'itsyourturn'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
